name: Zig CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Install system dependencies
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            sudo apt-get update
            sudo apt-get install -y libsdl2-dev libcurl4-openssl-dev
          elif [ "$RUNNER_OS" = "macOS" ]; then
            brew update
            brew install sdl2 curl
          else
            choco install -y sdl2 curl
          fi
      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.11.0
      - name: Run tests
        run: zig build -Doptimize=ReleaseFast test
      - name: Run benchmark
        run: zig build -Doptimize=ReleaseFast benchmark
      - name: Build binaries
        run: zig build -Doptimize=ReleaseFast
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binaries
          path: zig-out/bin/
