name: Zig CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libcurl4-openssl-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install sdl2 curl

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat -disableMetrics
          .\vcpkg\vcpkg.exe install curl:x64-windows sdl2:x64-windows
          $root = Resolve-Path .\vcpkg
          $inc  = Join-Path $root 'installed\x64-windows\include'
          $lib  = Join-Path $root 'installed\x64-windows\lib'
          $bin  = Join-Path $root 'installed\x64-windows\bin'
          "$bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          "INCLUDE=$inc;$env:INCLUDE" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "LIB=$lib;$env:LIB" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.11.0

      - name: Run tests
        run: zig build -Doptimize=ReleaseFast test

      - name: Run benchmark
        run: zig build -Doptimize=ReleaseFast benchmark

      - name: Build binaries
        run: zig build -Doptimize=ReleaseFast

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binaries
          path: zig-out/bin/
