name: Zig CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev libcurl4-openssl-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install sdl2 curl

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          choco install -y curl
          $curlRoot = Get-ChildItem "$env:ProgramData\chocolatey\lib\curl\tools" | Select-Object -First 1
          $curlInc = Join-Path $curlRoot.FullName 'include'
          $curlLib = Join-Path $curlRoot.FullName 'lib'
          $sdlVersion = '2.28.5'
          Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-$sdlVersion/SDL2-devel-$sdlVersion-VC.zip" -OutFile SDL2.zip
          Expand-Archive SDL2.zip -DestinationPath SDL2
          $sdlPath = Join-Path (Get-Location) "SDL2/SDL2-$sdlVersion"
          "$sdlPath\lib\x64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          "$curlRoot.FullName\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          "INCLUDE=$sdlPath\include;$curlInc;$env:INCLUDE" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "LIB=$sdlPath\lib\x64;$curlLib;$env:LIB" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.11.0

      - name: Run tests
        run: zig build -Doptimize=ReleaseFast test

      - name: Run benchmark
        run: zig build -Doptimize=ReleaseFast benchmark

      - name: Build binaries
        run: zig build -Doptimize=ReleaseFast

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binaries
          path: zig-out/bin/
